# Generated by Django 4.1.1 on 2022-10-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sucursal',
        ),
    ]
