# Generated by Django 4.1.1 on 2022-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_departamento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='images/usuarios/default.png', upload_to='images/usuarios'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=90, unique=True, verbose_name='Nombre Departamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.BooleanField(choices=[('True', 'Activo'), ('False', 'Inactivo')], default='True', max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=90, unique=True, verbose_name='Nombre Municipio'),
        ),
    ]
