# Generated by Django 4.1.1 on 2022-11-09 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_nombre'),
        ('usuarios', '0006_usuario_email_usuario_user'),
        ('facturas', '0002_detalle_compra_detalle_factura_devolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lote')),
                ('fechaExpiracion', models.DateField(verbose_name='Fecha Expiración')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('precio', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('precio', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='detalleFactura',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='numeroFactura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='empleado',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numeroSerie',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.DeleteModel(
            name='Detalle_Factura',
        ),
        migrations.AddField(
            model_name='facturadetalleventa',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura', verbose_name='Número Factura'),
        ),
        migrations.AddField(
            model_name='facturadetalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Detalle Factura'),
        ),
        migrations.AddField(
            model_name='facturadetallecompra',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura', verbose_name='Número Factura'),
        ),
        migrations.AddField(
            model_name='facturadetallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='detalleCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturadetalleventa', verbose_name='Detalle Compra'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='usuarios.usuario', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='usuarios.usuario', verbose_name='Empleado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detalle_Compra',
        ),
    ]
